-
  name:  'Article Rss Feed'
  uriPattern: '{node}.feed'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'feed'
  routeParts:
    'node':
      handler: Neos\Neos\FrontendRouting\FrontendNodeRoutePartHandlerInterface
  appendExceedingArguments: true
